# Generated by Django 4.1.1 on 2022-09-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
