# Generated by Django 4.1.1 on 2022-09-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0009_delete_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inicio',
        ),
        migrations.DeleteModel(
            name='productos',
        ),
    ]
