# Generated by Django 4.1.1 on 2022-09-17 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inicio',
        ),
    ]
