# Generated by Django 4.1.1 on 2022-09-25 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0016_rename_instagram_contactos_nombre_contactos_mensaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactos',
            name='telefono',
        ),
    ]
