# Generated by Django 4.1.1 on 2022-09-25 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0017_remove_contactos_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='mensaje',
            field=models.TextField(),
        ),
    ]
