# Generated by Django 4.1.1 on 2022-09-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0018_alter_contactos_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contraseña',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('contraseña', models.IntegerField()),
            ],
        ),
    ]
