# Generated by Django 4.1.1 on 2022-09-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0019_contraseña'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraseña',
            name='contraseña',
            field=models.CharField(max_length=6),
        ),
    ]
