# Generated by Django 4.1.1 on 2022-09-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0020_alter_contraseña_contraseña'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contraseña',
        ),
    ]
