# Generated by Django 4.1.1 on 2022-09-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0022_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='fecha',
        ),
        migrations.AddField(
            model_name='productos',
            name='presio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
