# Generated by Django 4.1.1 on 2022-09-25 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0023_remove_productos_fecha_productos_presio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='presio',
        ),
    ]
