# Generated by Django 4.1.1 on 2022-09-25 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0026_rename_presio_productos_presios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='presios',
            new_name='presio',
        ),
    ]
