# Generated by Django 4.1.1 on 2022-09-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0027_rename_presios_productos_presio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='presio',
        ),
        migrations.AddField(
            model_name='productos',
            name='fecha',
            field=models.DateField(default="2022-09-25"),
            preserve_default=False,
        ),
    ]
