# Generated by Django 4.1.1 on 2022-09-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0028_remove_productos_presio_productos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precios',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
