# Generated by Django 4.1.1 on 2022-09-25 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0029_productos_precios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='precios',
        ),
    ]
