# Generated by Django 4.1.1 on 2022-09-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0030_remove_productos_precios'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
