# Generated by Django 4.1.1 on 2022-09-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0031_productos_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha',
        ),
    ]
