# Generated by Django 4.1.1 on 2022-09-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0032_remove_usuario_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='fecha',
        ),
    ]
