# Generated by Django 4.1.1 on 2022-09-25 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0033_remove_productos_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
