# Generated by Django 4.1.1 on 2022-10-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0034_usuario_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
