# Generated by Django 4.1.1 on 2022-10-07 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0038_productos_productoimagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='idP',
        ),
    ]
