# Generated by Django 4.1.1 on 2022-10-08 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0040_alter_productos_productoimagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='productoImagen',
            new_name='imagen',
        ),
    ]
