# Generated by Django 4.1.1 on 2022-10-19 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0041_rename_productoimagen_productos_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
