# Generated by Django 4.1.1 on 2022-09-17 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productos',
        ),
    ]
