# Generated by Django 4.1.1 on 2022-09-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0005_inicio_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='inicio',
        ),
    ]
