# Generated by Django 4.1.1 on 2022-09-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appchoco', '0006_delete_inicio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productos',
        ),
        migrations.DeleteModel(
            name='usuario',
        ),
    ]
